### PR TITLE
Feature/hydration class

### PR DESCRIPTION
**Pull request by nichelicorn**
# Pull Request Template
## Description
* Add files for Hydration class and hydration test
🚧 These are not yet complete - WIP!!
## Type of change
- [x] New feature (non-breaking change which adds functionality)
## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
#### Please add appreciative feedback in the comment section of this PR after reviewing.

### CODE REVIEW

**Comment by nichelicorn** [comment]
🌚  I wanted to push up what I have so far on the Hydration class
🧠  I got a little stuck in a thought bubble about how to get the id. Does it make sense to create a separate method to grab the id from the hydration data?

**Comment by RMartin0717** [comment]
Great job getting the testing structure set up and pseudo-coding out the test

**Comment by RMartin0717** [comment]
> 🌚 I wanted to push up what I have so far on the Hydration class
> 🧠 I got a little stuck in a thought bubble about how to get the id. Does it make sense to create a separate method to grab the id from the hydration data?

Thanks for being specific in helping me find what to look for! I would say it might be best to include id as an additional parameter for the constructor and then you can give it whatever id you need when you create an instance of it

**Comment by RMartin0717** [comment]
Nice job testing multiple instances!

**Pull request merged**
